spring:
  profiles: 
    active: dev

---

server:
  port: 9009
spring:
  profiles: dev
  application:
    name: gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9000/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: gateway-dev
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
zuul: 
  #ignored-services: microservicecloud-dept
  ignored-services: "*"#将所有通过真实微服务的请求全部禁用     真实访问 http://网关应用url/真实注册服务Application名称/..
  routes: 
    mydept.serviceId: ITEM-DEV
    mydept.path: /mall/**#网关访问的真实路径 http://网关地址/mydept/..
    
info: 
  app.name: gateway
  company.name: www.xiaomiqiu.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$                                
---

server:
  port: 9010
spring:
  profiles: prod
  application:
    name: gateway-prod

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9000/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: gateway
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
zuul: 
  #ignored-services: microservicecloud-dept
  ignored-services: "*"#将所有通过真实微服务的请求全部禁用     真实访问 http://网关应用url/真实注册服务Application名称/..
  routes: 
    mydept.serviceId: ITEM-DEV
    mydept.path: /mall/**#网关访问的真实路径 http://网关地址/mydept/..
    
info: 
  app.name: gateway
  company.name: www.xiaomiqiu.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---

server:
  port: 9011
spring:
  profiles: test
  application:
    name: gateway-test
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9000/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: gateway
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
zuul: 
  #ignored-services: microservicecloud-dept
  ignored-services: "*"#将所有通过真实微服务的请求全部禁用     真实访问 http://网关应用url/真实注册服务Application名称/..
  routes: 
    mydept.serviceId: ITEM-DEV
    mydept.path: /mydept/**#网关访问的真实路径 http://网关地址/mydept/..
    
info: 
  app.name: gateway8089
  company.name: www.xiaomiqiu.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$