spring:
  profiles: 
    active: dev

---

server:
  port: 9010
    
spring:
   profiles: dev
   application:
    name: gateway

      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:9000/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: gateway
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
    
info: 
  app.name: gateway
  company.name: www.xiaomiqiu.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
 
 
 

